### PR TITLE
Feature/swift package manager

### PR DESCRIPTION
**Pull request by behzadardehei**

### CODE REVIEW

**Comment by NikKovIos** [comment]
Please leave as less changes as it could be. For example, i think, you can remove test files.

**Comment by NikKovIos** [comment]
Are you shure, that it necessary ?
```
#if os(iOS)
import Foundation
#endif
```

**Comment by behzadardehei** [comment]
> Are you sure, that it necessary ?
> 
> ```
> #if os(iOS)
> import Foundation
> #endif
> ```

Yes, because:

**Comment by behzadardehei** [comment]
Hi @NikKovIos 
Please let me know your thoughts?

**Pull request merged**
